### PR TITLE
Implemented `watch!()`

### PR DESCRIPTION
**Pull request by Ratysz**
More or less a breakpoint that will make the thread sleep until the file changes anywhere.

### CODE REVIEW

**Comment by Uriopass** [comment]
Would it be possible to add something about it in the README ? Other than that, the implementation LGTM.

**Comment by Ratysz** [comment]
Added the note. Not sure on wording, "If continuously looping the code is not necessary" vs "If looping the code continuously is not necessary". English hard.

**Comment by Uriopass** [comment]
I would just talk about it as another functionality the crate provides, the user is left to wonder about the possibilities.

Something like:
"`inline_tweak` also provides a `watch!()` macro which sleeps until the file is modified, akin to a breakpoint."

**Comment by Uriopass** [comment]
Thanks ! 👍

**Comment by Uriopass** [comment]
Published in [1.0.2](https://crates.io/crates/inline_tweak)

**Pull request merged**
