### PR TITLE
Fix wasm32 runtime panic due to Time not working there

### PR DESCRIPTION
**Pull request by markusstephanides**

### CODE REVIEW

**Comment by Uriopass** [comment]
Without instant working, that'd mean the file is parsed on every tweak invocation which is incredibly heavy. Can you even parse files from wasm? Did you try out this change and successfully make it work on wasm? What was your setup?

**Comment by markusstephanides** [comment]
Afaik you can't parse files from wasm (except if they are served from a file server but you wouldn't serve source files anyway).
That's why I would just disable the functionality completely if `target_arch` is `wasm32` - I guess similiar to how `tweak!` works in `release` builds.

**Comment by Uriopass** [comment]
Got it :+1: 

Could you make this more explicit by changing the cfg on the `inline_tweak!` macro definition (just like for release)

And updating the README and changelog. Thanks :)

**Comment by markusstephanides** [comment]
Sure, that makes much more sense and is easier to read. Hope I didn't forget anything!

**Comment by Uriopass** [comment]
Thanks!

**Comment by markusstephanides** [comment]
No worries, really helpful crate you created with a really good approach. Helps me with game development to hot reload damage values, positions, colors, strings. Improves iteration productivity so much!!!

**Pull request merged**
