### PR TITLE
Identify tweaks by position in file instead of position in line

### PR DESCRIPTION
**Pull request by benfrankel**
This change makes tweak identification slightly more resilient to simple changes to a file. Specifically, it supports the use case where rustfmt runs automatically on save, which may move tweaks to different lines.

There's most likely an additional performance cost to searching the entire file per tweak instead of just the line the tweak is on, but that seems acceptable for my use case. This could probably be optimized by updating the tweak cache while counting tweaks so that the file only has to be re-read once.

### CODE REVIEW

**Comment by Uriopass** [comment]
I actually wanted to do this but seems like you implemented it first! This does mean parsing is a bit more expensive but file changes happen so rarely anyway this is fine.  
Implementation LGTM.

Thank you! I'll publish new 1.0.3 with this.

EDIT: published ✔️

**Comment by benfrankel** [comment]
I just noticed that there's a bug with the way positions are calculated. When a `tweak!()` is called for the first time, its position is determined relative to the other `tweak!()`s in the file that have already been called. The position is stored in `VALUES` and never changed. This means that if `tweak!()`s aren't initially called in the order they appear in the file, it's possible for e.g. all `tweak!()`s to have position `0`.

The bug existed before this change, but its scope was limited to `tweak!()`s on the same line; this change increases the scope to `tweak!()`s in the same file, which is more likely to lead to incorrect behavior.

This could be partially fixed by updating the other `tweak!()`s' positions when a new `tweak!()` is inserted, but then positions would still be incorrect until all `tweak!()`s in a file are run (which might not happen if e.g. one of the `tweak!()`s is on a rare code path). I think a better way to fix this would be to load all `tweak!()` positions on the first call to `tweak!()`. As a bonus, that would allow the string `tweak!(` to appear in strings and comments without interfering with positions.

**Comment by Uriopass** [comment]
Oh darn! I didn't realize this. I'll yank the latest publish since it's wrong too often (two tweaks in a file) and update.

**Comment by Uriopass** [comment]
What do you think of https://github.com/Uriopass/inline_tweak/commit/b4beffadb9c43980301bd22c41902b91c508a079 ?

**Comment by benfrankel** [comment]
Looks good, though it won't work for `inline_tweak::tweak!()` because then the column number from parsing won't match the column number from the macro. I'm not sure how that can be fixed.

Also a minor comment, I think `parse_tweaks` can be simplified by replacing `line.split("tweak!(")` with `line.match_indices("tweak!(")`.

**Comment by Uriopass** [comment]
Wow thank you for `match_indices`! I knew it existed but couldn't find the name.

About the `column!` macro returning the leftmost column that's indeed a problem, I think I can parse differently to check for both variants. For example by taking into account any path before the `tweak!`

**Comment by Uriopass** [comment]
Fixed in https://github.com/Uriopass/inline_tweak/commit/3cd1d26a2736cdaad10f56c14fa2a9f5b726f3d6
I made a small mistake (did unwrap_or(column) instead of unwrap_or(0)) but I published it too early and it should never happen anyway because of rustfmt. fixed it in a later commit but i'll wait for something else to add.

**Pull request merged**
